### ISSUE TITLE
No implicit dependencies.

### ISSUE THREAD

**Issue by LastDragon-ru** [LastDragon-ru/lara-asp#151]
Some time ago injection of `Container`/`Config` (and some other) were replaced by the direct call `Container::getInstance()` to be compatible with Octane (#38). The main problem with the current approach - implicit dependencies and (more important) implicit config (`Container::getInstance()->make(Repository::class)->get(...)`).

Recently I have reviewed all these places and looks like it is possible to convert all of them into explicit 🎉

- [x] Switch to resolvers instead of `Container::getInstance()` (#160)
- [x] #152
- [x] Model Casts (`serializer`) (77490f68ec78b1d481f2b6aa8cb456b35ab40480)
- [x] Migrations (to use SQL) (#167)
- [x] GraphQL Scalars (eg `StreamOffset`) (#157, #160, #161)
- [x] Routes (`spa`) (#160)
